#!/usr/bin/python
import sys
import subprocess
import os

PATH      = os.path.dirname(os.path.realpath(__file__))
os.chdir(PATH)

if len(sys.argv) > 1:
	# Initial Input CBR value
    	INITIAL_CBR	=	sys.argv[1]
else:
   	print "Please provide a starting CBR number less than 10.5"
	sys.exit()

# Find out the path of NS
NS			= 	subprocess.check_output("whereis ns | awk '{print $2}'", shell=True).strip()

# Set the Maximum value of CBR
MAXCBR			=	10.5

# Increment factor
INCREMENT_FACTOR	=	0.5

# CBR Counter
cbr 			=	float(INITIAL_CBR)

# Trace file
TRACEFILE		=	"renoreno.tr"


# Flush the old file 
subprocess.check_output("rm -f reno1throughput.txt reno1droprate.txt reno1latency.txt",shell=True)
subprocess.check_output("rm -f reno2throughput.txt reno2droprate.txt reno2latency.txt",shell=True)


#Create file descriptors for the while loop to write data
f1 = open("reno1throughput.txt",'a')
f2 = open("reno2throughput.txt",'a')
pdd1 = open("reno1droprate.txt",'a')
pdd2 = open("reno2droprate.txt",'a')
l1 = open("reno1latency.txt",'a')
l2 = open("reno2latency.txt",'a')

while (cbr < MAXCBR):
	# Call the TCL script

	subprocess.check_output(NS+" renoreno.tcl "+str(cbr),shell=True).strip()

	# Throughput measurements
	reno1_kbps_throughput = subprocess.check_output("awk -f tcp-tp-0-3.awk " + TRACEFILE,shell=True).strip()
	reno2_kbps_throughput = subprocess.check_output("awk -f tcp-tp-4-5.awk " + TRACEFILE,shell=True).strip()

	reno1_kbps_throughput = round(float(reno1_kbps_throughput),2)
	reno2_kbps_throughput = round(float(reno2_kbps_throughput),2)

	f1.write(str(cbr)+ " " + str(reno1_kbps_throughput)+"\n")

	f2.write(str(cbr)+ " " + str(reno2_kbps_throughput)+"\n")


	# Packet drop measurements
	pd1 = subprocess.check_output("awk '/^d/&&$3==1&&$5==\"tcp\"&&$8==1' "+TRACEFILE+" | wc -l",shell=True).strip()
	ps1 = subprocess.check_output("awk '/^-/&&$3==0&&$5==\"tcp\"&&$8==1' "+TRACEFILE+" | wc -l",shell=True).strip()
	drop_rate_reno1 = float(pd1)/float(ps1)
	pdd1.write(str(cbr)+ " " + str(round ((drop_rate_reno1*100),2))+"\n")

	pd2 = subprocess.check_output("awk '/^d/&&$3==1&&$5==\"tcp\"&&$8==3' "+TRACEFILE+" | wc -l",shell=True).strip()
	ps2 = subprocess.check_output("awk '/^-/&&$3==4&&$5==\"tcp\"&&$8==3' "+TRACEFILE+" | wc -l",shell=True).strip()
	drop_rate_reno2 = float(pd2)/float(ps2)
	pdd2.write(str(cbr)+ " " + str(round ((drop_rate_reno2*100),2))+"\n")



	latency1 = subprocess.check_output("awk -f tcp-lat-0-3.awk " + TRACEFILE,shell=True).strip()
	latency1_ms = round((float(latency1) * 1000),3)
	l1.write(str(cbr)+ " " + str(latency1_ms)+"\n")

	latency2 = subprocess.check_output("awk -f tcp-lat-4-5.awk " + TRACEFILE,shell=True).strip()
	latency2_ms = round((float(latency2) * 1000),3)
	l2.write(str(cbr)+ " " + str(latency2_ms)+"\n")


	cbr=cbr+INCREMENT_FACTOR

# Close the open file descriptors
f1.close()
f2.close()
pdd1.close()
pdd2.close()
l1.close()
l2.close()

# Combine the throughput results of both TCP variants
subprocess.check_output("paste reno1throughput.txt reno2throughput.txt | awk '{print $1,$2,$4}' > renorenotcp-tp.txt",shell=True).strip()

# Combine the Packet Drop rate results of both TCP variants
subprocess.check_output("paste reno1droprate.txt reno2droprate.txt | awk '{print $1,$2,$4}' > renorenotcp-pd.txt",shell=True).strip()
 
# Combine the Packet Drop rate results of both TCP variants
subprocess.check_output("paste reno1latency.txt reno2latency.txt | awk '{print $1,$2,$4}' > renorenotcp-l.txt",shell=True).strip()

# Cleanup

# Remove the helper files (OPTIONAL)
subprocess.check_output("rm -rf reno1throughput.txt reno2throughput.txt",shell=True)
subprocess.check_output("rm -rf reno1droprate.txt reno2droprate.txt",shell=True)
subprocess.check_output("rm -rf reno1latency.txt reno2latency.txt",shell=True)

#l.close()

print "==================================="
print "End of TCP Reno-Reno CBR Variations"
print "==================================="
