#!/usr/bin/python

REMOTE_PORT = 80
REMOTE_HOST = "fring.ccs.neu.edu"

# HTTP STATUS CODES
HTTP_STATUS_OK          = '200'
HTTP_MOVED_PERMANENTLY  = '301'
HTTP_MOVED_TEMPORARILY  = '302'
HTTP_FORBIDDEN          = '403'
HTTP_NOT_FOUND          = '404'
HTTP_SERVER_ERROR_RETRY = '500'

HTTP_PROTOCOL = "HTTP/1.1"
PERSISTENT_CONNECTION_HEADER = "Connection: close"
# PERSISTENT_CONNECTION_HEADER = "Connection: keep-alive"
CRLF        = "\r\n"
LOGIN_PAGE  = "/accounts/login/?next=/fakebook/"

FORM_ACTION = LOGIN_PAGE
GET_LOGIN_PAGE = "GET "+LOGIN_PAGE+" "+HTTP_PROTOCOL+CRLF+PERSISTENT_CONNECTION_HEADER+CRLF+"Host: "+REMOTE_HOST+CRLF+CRLF

FLAG_COUNT = 5